version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: practica7
    command: 'npm start'
    ports:
      - 3000:3000
    volumes:
      - .:/app
