name: build-artifacts
on:
  push:
    branches:
      - master
      - develop
    tags:
      - 0.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - create temporary artifact
        run: mkdir dist
      - name: Step 2 - add artifacts to pusblish
        run: copy ../Practica4 /dist
      - name: Step 3 - use the upload artifact
        uses: actions/uploado-artifact@v2
        with:
          name: dist
          path: dist
